# Generated by Django 3.2.5 on 2022-01-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questao7', '0002_marker_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='nome',
            new_name='name',
        ),
    ]
