# Generated by Django 3.2.5 on 2022-01-05 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome ')),
                ('admissao', models.DateField(default=datetime.datetime.now, verbose_name='Admissao')),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questao1.cargos')),
            ],
        ),
    ]
