# Generated by Django 3.2.5 on 2022-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questao1', '0002_auto_20220105_2011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargos',
            table='Cargos',
        ),
        migrations.AlterModelTable(
            name='pessoas',
            table='Pessoas',
        ),
    ]
